name: dispatch-lab
on: 

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 
      - name: Set up
        run : |
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"
          # Add your deployment logic here
